version: '2'
services:

  web:
    container_name: waproject-api
    build: docker/dev
    ports:
      - "3001:3000"
      - "5859:5859"
    env_file:
      - .env
    volumes:
      - .:/src
      - ./docker/dev/start.sh:/usr/local/bin/start.sh
    links:
      - database

  database:
    container_name: waproject-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=waproject
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123mudar
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"